### ISSUE TITLE
When calling converter.convert() I encountered a wierd problem

### ISSUE THREAD

**Issue by Derricktao** [sithu31296/PyTorch-ONNX-TFLite#1]
HI, thank you for the detailed implementation
I was trying to convert the torch model to a tflite quantization for Coral Edge TPU.
However, I found when I call the converter.convert(), it will pop up a 
Javascript Error: Too much recursion. 
Did you encounter this problem before?

**Comment by sithu31296** [comment]
Thanks for your interest in this repo! I've updated the repo to latest onnx-tf==1.7.0. Since onnx-tf==1.7.0 introduces SavedModel format, you can now directly convert tf to tflite. Can you please try again with the updated version? If you still encounter an error, please upload onnx model file. I haven't faced like this error before.

**Comment by Derricktao** [comment]
Hi, my onnx is updodate :/    how can I upload the onnx file so you can take a look?

**Comment by sithu31296** [comment]
You can upload on hosting site and share the link.

**Comment by Derricktao** [comment]
This is the onnx model link:https://drive.google.com/file/d/1kDduxEsdc9TI29s-2gKuXgioLKsRlURp/view?usp=sharing
And this is a sample input image: https://drive.google.com/file/d/1ryNpzdhtS6qltKw0yjySXi_yjJAHxC0O/view?usp=sharing

**Comment by sithu31296** [comment]
I did not encounter your JavaScriptError but your model cannot be converted to tflite using TFLite ops. If I try to convert, I get an error like this:

`tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite("Pad_1@__inference___call___1010" at "PartitionedCall@__inference_signature_wrapper_1167") at "PartitionedCall")): operand #0 does not dominate this use   
<unknown>:0: note: loc("PartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("Pad_1@__inference___call___1010" at "PartitionedCall@__inference_signature_wrapper_1167") at "PartitionedCall")): operand defined here`

Pad_1 ops (i don't know where exactly) caused the error. This may mean that this ops is not currently supported in tflite.

To use TF ops during conversion, add the following line:

`converter.target_spec.supported_ops = [
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TF ops
]`

But this may effect the performance.

**Comment by Derricktao** [comment]
Thank you for your response, I did try with the TF ops, but it pop another error when deloying on the Edge Tpu (Coral Usb accelerator) since the ops is not supported..

**Comment by sithu31296** [comment]
I don't have an experience with Coral Edge TPU. You can open an issue in official tensorflow since pytorch to tf conversion is successful and this is an issue with tflite conversion.
