### ISSUE TITLE
converting .pt file to .tflite file

### ISSUE THREAD

**Issue by SeraaAlmalki** [sithu31296/PyTorch-ONNX-TFLite#3]
Hello
first, I'd like to thank you all for your hard work.
second, I'm still learning about python and all kind of models 
I've seen the instructions about converting PyTorch -> ONNX -> TF -> TFLite
here: https://github.com/sithu31296/PyTorch-ONNX-TFLite
and I'm still confused on how to do that, looked up online but there is no step-by-step tutorial
if anyone can explain it to me because I've been really struggling with it 
thank you

**Comment by sithu31296** [comment]
I don't know what are you talking about. I wrote the instructions step by step and there is even conversion scripts in https://github.com/sithu31296/PyTorch-ONNX-TFLite/tree/master/conversion. I suggest try to use pytorch and onnx first instead of going to tflite if you are new to this field.

**Comment by thaingoc2604** [comment]
i have convert on colab hay pycharm and And do I need to install anything else to be able to run the above code?
Thanks!
